### PR TITLE
`purupuru`: Refactor effects, fix first-party device support

### LINKED ISSUE #1064: rumble calls disrupts maple controller readings
how to reproduce: 

edit the file: examples/dreamcast/rumble/rumble.c and uncomment the two calls to `plx_fcxt_setsize` (calling this causes the text rendering to not show). 

Then compile and run the rumble.elf program. 

If  you then rapidly press `B` button, which sends a 0x00000000 signal to the purupuru on each press, the screen starts flickering with "Please attach a controller!" or "Please attach a rumbler!"
It does the same thing when using the `A` button to send the currently configured rumble signal.

My assumption is that sending purupuru commands make KOS think that the devices have been removed for a number of frames. 

Note: I've only tried this with original purupuru-packs, I don't have other makes to test.

### PR DESCRIPTION
**Pull request by QuzarDC**
Big fixup to rumble support:
- Added error checking in the maple command irq handler. These were essential to diagnosing the illegal commands that we were sending to official rumble packs. If they trip it likely indicates something that we should be doing differently.
- Cleaned up rumble driver to use stdint types.
- Added new struct members based on info provided by @megavolt85 [here](https://github.com/KallistiOS/KallistiOS/pull/1052#issuecomment-2913983412) I've updated the documentation to include what I've found of error conditions.
- Deprecate old struct members.
- Update `purupuru_rumble` to check for values that would trigger a hardware error on official rumble packs. This is what corrects use with official packs. Previously we were using just a flat `0x00000000` to stop rumbling. On third party rumbles, they just didn't care, but on first-party the motor field triggers an error if set to 0 (and we don't recover from those errors well in the root maple driver).
- Update rumble example to reflect new findings.

This should close #1064 and #941.

From my testing in this PR there are a few big sets of future improvements that should be undertaken as followups (but shouldn't hold back this bugfixing):
- Better handle a maple device throwing an error. Currently we just don't do anything for it. But it seems that it may be a good use case for the same reset command I've implemented in #772 . Something like 'if a device repeatedly errors, send a reset command to it'. (I've opened #1147 to try to block similar errors with VMS devices)
- I found that the rumble pack appears to allow various other commands like `MAPLE_RESPONSE_DATATRF` and `MAPLE_COMMAND_BWRITE` which likely have to do with the 'Auto-Stop Timeout' or other patterns. That it can take larger sets of data would indicate it's possible to upload some sort of ongoing pattern or sequence to the device rather than repeatedly sending individual effects to build a sequence.
- Update the rumble example to display and allow setting of the individual struct fields rather than the raw bitfield.
- The rumble example has a bug where it will periodically drop all the text under the hex values and stop updating the screen. Usually happens on device disconnect but also seemingly randomly on sending a stop. After this point the example continues to function and is intractable a bit via the printf output but appears to hang visually.

### CODE REVIEW

**Comment by QuzarDC** [comment]
This fails whitespace CI due to the (intentional) changes to the rumble example printouts of the effect data:

```
quzar@Centurion-IV:~/dcdev/KallistiOS$ git diff HEAD~1 > diff.txt
quzar@Centurion-IV:~/dcdev/KallistiOS$ git diff -w HEAD~1 >diffw.txt
quzar@Centurion-IV:~/dcdev/KallistiOS$ diff diff.txt diffw.txt
122,125d121
< -
< -  printf("  .fx1_pulse       =  %u,\n", fields.fx1_pulse);
< -  printf("  .fx1_powersave   =  %u,\n", fields.fx1_powersave);
< -  printf("  .fx1_intensity   =  %u,\n", fields.fx1_intensity);
129,132c125,127
< -  printf("  .fx2_lintensity  =  %u,\n", fields.fx2_lintensity);
< -  printf("  .fx2_pulse       =  %u,\n", fields.fx2_pulse);
< -  printf("  .fx2_uintensity  =  %u,\n", fields.fx2_uintensity);
< -  printf("  .fx2_decay       =  %u,\n", fields.fx2_decay);
---
> -  printf("  .fx1_pulse       =  %u,\n", fields.fx1_pulse);
> -  printf("  .fx1_powersave   =  %u,\n", fields.fx1_powersave);
> -  printf("  .fx1_intensity   =  %u,\n", fields.fx1_intensity);
137a133,137
> -  printf("  .fx2_lintensity  =  %u,\n", fields.fx2_lintensity);
> -  printf("  .fx2_pulse       =  %u,\n", fields.fx2_pulse);
> -  printf("  .fx2_uintensity  =  %u,\n", fields.fx2_uintensity);
> -  printf("  .fx2_decay       =  %u,\n", fields.fx2_decay);
> -
quzar@Centurion-IV:~/dcdev/KallistiOS$

**Review by dfchil — CHANGES_REQUESTED** [review]
Disregard this. I was too hasty.

File: kernel/arch/dreamcast/include/dc/maple/purupuru.h [hunk 1]
```diff
@@ -49,114 +52,56 @@ __BEGIN_DECLS
...
+        uint8_t fpow    : 3;
+        /** \brief Convergent vibration. The rumble will get weaker until it stops. */
+        bool    conv    : 1;
+
+        /** \brief Vibration frequency. for most purupuru 4-59. */
+        uint8_t freq;
+        /** \brief Vibration inclination period. */
+        uint8_t inc;
+    };
 } purupuru_effect_t;
```
Comment (dfchil) [inline kernel/arch/dreamcast/include/dc/maple/purupuru.h]: Could you change this to this: 

```c
typedef union purupuru_effect  {
    /** \brief Access the raw 32-bit value to be sent to the puru */
    uint32_t raw;
    /** \brief Deprecated old structure which has been inverted now to union with raw. */
    struct {
        uint8_t special     __depr("Please see purupuru_effect_t which has new members.");
        uint8_t effect1     __depr("Please see purupuru_effect_t which has new members.");
        uint8_t effect2     __depr("Please see purupuru_effect_t which has new members.");
        uint8_t duration    __depr("Please see purupuru_effect_t which has new members.");
    };
    struct {
        /** \brief Continuous Vibration. When set vibration will continue until stopped */
        bool    cont    : 1;
        /** \brief Reserved. Always 0s */
        uint32_t res    : 3;
        /** \brief Motor number. 0 will cause an error. 1 is the typical setting. 4-bits. */
        uint32_t motor  : 4;
        /** \brief Backward direction (- direction) intensity setting bits. 0 stops vibration. 3-bits. */
        uint32_t bpow   : 3;
        /** \brief Divergent vibration. The rumble will get stronger until it stops. */
        bool    div     : 1;
        /** \brief Forward direction (+ direction) intensity setting bits. 0 stops vibration. 3-bits. */
        uint32_t fpow   : 3;
        /** \brief Convergent vibration. The rumble will get weaker until it stops. */
        bool    conv    : 1;
        /** \brief Vibration frequency. For most purupuru the range is 4-59. */
        uint8_t freq;
        /** \brief Vibration inclination period. */
        uint8_t inc;
    };
} purupuru_effect_t;
```

Comment (dfchil) [reply kernel/arch/dreamcast/include/dc/maple/purupuru.h]: The primary change is to use uint32_t where the bit-size doesn't fit any well known type. Originally I thought that they should all be changed to uint32_t, but I realized that having types that fit the bit-size is a nice hint to the user.

**Review by dfchil — CHANGES_REQUESTED** [review]
I've done a complete rewrite of the rumble example based on this PR, as you can see here: [git@github.com:dfchil/KallistiOS.git](https://github.com/dfchil/KallistiOS/tree/First_rumble_party), I want to make a PR for that once this PR goes through. 

My one request for change (see my comment) is more of a suggestion, if you decline it, I'll happily accept this PR, it is up to you.

File: kernel/arch/dreamcast/include/dc/maple/purupuru.h (hunk 1 above)
Comment (QuzarDC) [reply kernel/arch/dreamcast/include/dc/maple/purupuru.h]: Yup, makes sense. I was doing parts of `uint8_t`s because I was treating it as four `uint8_t`s rather than the 'raw' value.

I took the opportunity to also add a static assert to validate the size of the struct in order to protect from the chance that this would trigger padding somewhere.

I did leave the spacing separating the two 8-bit chunks in order to help readability of comparing them to the older versions.

**Review by dfchil — APPROVED** [review]
Good work. I look forwards to building on this =)
