### PR TITLE
Fix barrier example

### LINKED ISSUE #1079: `basic/threading/barrier` example hangs/crashes
Previously I was getting a hang at this same point. Now, after rebuilding most of my environment it crashes instead.
```Joining threads...
Thread[2]: After barrier[4]: NONSERIAL!
Thread[1]: After barrier[4]: NONSERIAL!
Thread[3]: After barrier[4]: NONSERIAL!
Unhandled exception: PC 8c01ed1e, code 1, evt 0100
 R0-R7: 00000000 00000001 00000001 00003fff 400000f1 0c009484 00000001 400000f0
 R8-R15: 8c085320 00000000 40000001 8cffffa3 8cffff9c 00000000 8c062f20 8cffff84
 SR 400000f0 PR 8c01ed14
Stack Trace: frame pointers not enabled!

Encountered Data address error (write). Use this template terminal command to help diagnose:

        $KOS_ADDR2LINE -f -C -i -e prog.elf 8c01ed1e 8c01ed14
```

### PR DESCRIPTION
**Pull request by QuzarDC**
`thd_join` is meant to take a `void **` by passing instead `bool *` you can get all sorts of bad stuff when the data overflows the bool. Fixes #1079 .

### CODE REVIEW

**Review by gyrovorbis — DISMISSED** [review]
HOLY CRAP. Good find!!!! What a subtle little screw-up!

File: examples/dreamcast/basic/threading/barrier/barrier.c [hunk 1]
```diff
@@ -134,7 +134,7 @@ int main(int argc, char* argv[]) {
 
     printf("Joining threads...\n");
     for(unsigned  t = 0; t < THREAD_COUNT - 1; ++t) {
-        bool thread_ret;
+        void *thread_ret;
         const int ret = thd_join(threads[t], (void**)&thread_ret);
```
Comment (pcercuei) [inline examples/dreamcast/basic/threading/barrier/barrier.c]: Minus comment but you can drop the `(void **)` cast now.

Comment (QuzarDC) [reply examples/dreamcast/basic/threading/barrier/barrier.c]: oops! Absolutely.
